### ISSUE TITLE
where to find the file "/home/manager/Phylogenetics/AF1b_C1_dates.txt"?

### ISSUE THREAD

**Issue by liamxg** [josephhughes/viral-bioinformatics-training#2]
@josephhughes @spyros-lytras

**Comment by spyros-lytras** [comment]
@KathrynCampbell you may be able to answer this? thanks!

**Comment by KathrynCampbell** [comment]
@liamxg I've now added this to the Phylogenetics folder in this repo. There will likely be some more files you'll need if you're following the whole course as these were originally uploaded to a virtual machine. Let me know what you need as you progress by tagging me in an issue (@KathrynCampbell) and I'll add them for you!

**Comment by liamxg** [comment]
@KathrynCampbell thanks, yes, there are some more files that I needed, when I following the whole course, I will tell you, very appreciated for your help.
